In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
pd.set_option('display.max_columns', 22)
pd.set_option('display.max_rows', 300)

In [2]:
data = pd.read_csv("../data_sets/Employee_Compensation_SF.csv")

In [3]:
data.head()

Year Type  Year  Organization Group Code    Organization Group  \
0    Fiscal  2016                        1     Public Protection   
1  Calendar  2013                        5  Culture & Recreation   
2  Calendar  2015                        4      Community Health   
3    Fiscal  2015                        4      Community Health   
4    Fiscal  2014                        5  Culture & Recreation   

  Department Code                      Department  Union Code  \
0             DAT               District Attorney       311.0   
1             ART                 Arts Commission       790.0   
2             DPH                   Public Health       535.0   
3             DPH                   Public Health       250.0   
4             REC  Recreation and Park Commission       790.0   

                               Union Job Family Code  \
0   Municipal Attorneys' Association            8100   
1   SEIU - Miscellaneous, Local 1021            1800   
2  SEIU - Human Services, Local 1021            2900   
3  SEIU - Health Workers, Local 1021            2200   
4   SEIU - Miscellaneous, Local 1021            3200   

                      Job Family Job Code                          Job  \
0                  Legal & Court     8177    Attorney (Civil/Criminal)   
1  Budget, Admn & Stats Analysis     1844  Senior Management Assistant   
2                 Human Services     2903           Eligibility Worker   
3               Medical & Dental     2202                  Dental Aide   
4                     Recreation     3279            Recreation Leader   

   Employee Identifier   Salaries  Overtime  Other Salaries  Total Salary  \
0                49919  114473.16       0.0         1500.00     115973.16   
1                 1225   84077.11       0.0            0.00      84077.11   
2                34873    9980.17       0.0          798.43      10778.60   
3                51145    2873.41       0.0            0.00       2873.41   
4                48705    6701.85       0.0          176.70       6878.55   

   Retirement  Health/Dental  Other Benefits  Total Benefits  \
0    21025.98       13068.80         9368.71        43463.49   
1    16587.30       12457.73         6931.91        35976.94   
2        0.00        2254.93          835.11         3090.04   
3        0.00         622.63          222.46          845.09   
4        0.00        2711.66          538.43         3250.09   

   Total Compensation  
0           159436.65  
1           120054.05  
2            13868.64  
3             3718.50  
4            10128.64

In [4]:
data.shape

(291825, 22)

In [5]:
data.columns

Index(['Year Type', 'Year', 'Organization Group Code', 'Organization Group',
       'Department Code', 'Department', 'Union Code', 'Union',
       'Job Family Code', 'Job Family', 'Job Code', 'Job',
       'Employee Identifier', 'Salaries', 'Overtime', 'Other Salaries',
       'Total Salary', 'Retirement', 'Health/Dental', 'Other Benefits',
       'Total Benefits', 'Total Compensation'],
      dtype='object')

In [6]:
print(len(data.columns))

22


In [7]:
le = LabelEncoder()
data['Organization Group']= le.fit_transform(data['Organization Group'])

In [8]:
data.drop(data.columns[[0, 4, 5, 7, 8, 9, 10, 11]], axis = 1, inplace = True)

In [9]:
data.head(100)

Year  Organization Group Code  Organization Group  Union Code  \
0   2016                        1                   5       311.0   
1   2013                        5                   1       790.0   
2   2015                        4                   0       535.0   
3   2015                        4                   0       250.0   
4   2014                        5                   1       790.0   
5   2013                        2                   6        21.0   
6   2015                        5                   1       790.0   
7   2014                        6                   2        21.0   
8   2015                        1                   5       911.0   
9   2014                        1                   5       498.0   
10  2015                        2                   6       790.0   
11  2013                        2                   6        21.0   
12  2015                        5                   1       261.0   
13  2013                        2                   6       253.0   
14  2016                        3                   4        22.0   
15  2014                        6                   2        16.0   
16  2015                        2                   6       253.0   
17  2014                        2                   6       790.0   
18  2014                        1                   5       311.0   
19  2015                        2                   6        38.0   
20  2016                        4                   0       791.0   
21  2015                        3                   4       535.0   
22  2013                        5                   1         4.0   
23  2015                        4                   0       791.0   
24  2014                        4                   0       250.0   
25  2013                        3                   4       790.0   
26  2016                        4                   0       250.0   
27  2015                        3                   4         1.0   
28  2013                        1                   5       790.0   
29  2013                        4                   0        21.0   
30  2014                        4                   0        21.0   
31  2014                        4                   0       790.0   
32  2013                        3                   4       535.0   
33  2015                        3                   4       790.0   
34  2014                        5                   1       790.0   
35  2016                        4                   0        39.0   
36  2014                        1                   5       911.0   
37  2016                        5                   1       790.0   
38  2015                        2                   6        21.0   
39  2015                        1                   5       790.0   
40  2015                        5                   1       790.0   
41  2014                        2                   6       790.0   
42  2015                        2                   6       790.0   
43  2013                        2                   6       856.0   
44  2014                        3                   4       790.0   
45  2013                        1                   5       911.0   
46  2014                        4                   0        21.0   
47  2013                        4                   0       790.0   
48  2013                        2                   6        21.0   
49  2015                        4                   0       791.0   
50  2014                        4                   0       790.0   
51  2013                        3                   4         1.0   
52  2013                        3                   4         1.0   
53  2013                        3                   4         1.0   
54  2015                        1                   5       911.0   
55  2013                        1                   5       798.0   
56  2015                        4                   0       250.0   
57

In [10]:
data.shape

(291825, 14)

In [11]:
new_data = data.dropna()

In [12]:
new_data.shape

(291782, 14)

In [13]:
print(len(new_data.columns))

14


In [14]:
num = new_data._get_numeric_data()
num[num < 0] = 0
new_data.head()

Year  Organization Group Code  Organization Group  Union Code  \
0  2016                        1                   5       311.0   
1  2013                        5                   1       790.0   
2  2015                        4                   0       535.0   
3  2015                        4                   0       250.0   
4  2014                        5                   1       790.0   

   Employee Identifier   Salaries  Overtime  Other Salaries  Total Salary  \
0                49919  114473.16       0.0         1500.00     115973.16   
1                 1225   84077.11       0.0            0.00      84077.11   
2                34873    9980.17       0.0          798.43      10778.60   
3                51145    2873.41       0.0            0.00       2873.41   
4                48705    6701.85       0.0          176.70       6878.55   

   Retirement  Health/Dental  Other Benefits  Total Benefits  \
0    21025.98       13068.80         9368.71        43463.49   
1    16587.30       12457.73         6931.91        35976.94   
2        0.00        2254.93          835.11         3090.04   
3        0.00         622.63          222.46          845.09   
4        0.00        2711.66          538.43         3250.09   

   Total Compensation  
0           159436.65  
1           120054.05  
2            13868.64  
3             3718.50  
4            10128.64

In [15]:
new_data['Organization Group'].unique()

array([5, 1, 0, 6, 2, 4, 3])

In [16]:
#np.isnan(data)

In [17]:
#np.where(np.isnan(data))

In [18]:
#np.nan_to_num(data)

In [19]:
#new_data[new_data < 0] = 0

In [20]:
array = new_data.values

In [21]:
array

array([[2.0160000e+03, 1.0000000e+00, 5.0000000e+00, ..., 9.3687100e+03,
        4.3463490e+04, 1.5943665e+05],
       [2.0130000e+03, 5.0000000e+00, 1.0000000e+00, ..., 6.9319100e+03,
        3.5976940e+04, 1.2005405e+05],
       [2.0150000e+03, 4.0000000e+00, 0.0000000e+00, ..., 8.3511000e+02,
        3.0900400e+03, 1.3868640e+04],
       ...,
       [2.0140000e+03, 4.0000000e+00, 0.0000000e+00, ..., 1.0966900e+03,
        2.3199600e+03, 1.6485340e+04],
       [2.0150000e+03, 4.0000000e+00, 0.0000000e+00, ..., 6.4189500e+03,
        3.4995500e+04, 1.1386136e+05],
       [2.0140000e+03, 2.0000000e+00, 6.0000000e+00, ..., 4.3639000e+02,
        3.1374900e+03, 8.7947500e+03]])

In [22]:
X1 = array[:,0:2]
X2 = array[:, 3:14]
X = np.concatenate((X1, X2), axis=1)

Y = array[:,2]

In [23]:
Y

array([5., 1., 0., ..., 0., 0., 6.])

In [24]:
X

array([[2.0160000e+03, 1.0000000e+00, 3.1100000e+02, ..., 9.3687100e+03,
        4.3463490e+04, 1.5943665e+05],
       [2.0130000e+03, 5.0000000e+00, 7.9000000e+02, ..., 6.9319100e+03,
        3.5976940e+04, 1.2005405e+05],
       [2.0150000e+03, 4.0000000e+00, 5.3500000e+02, ..., 8.3511000e+02,
        3.0900400e+03, 1.3868640e+04],
       ...,
       [2.0140000e+03, 4.0000000e+00, 7.9100000e+02, ..., 1.0966900e+03,
        2.3199600e+03, 1.6485340e+04],
       [2.0150000e+03, 4.0000000e+00, 7.9000000e+02, ..., 6.4189500e+03,
        3.4995500e+04, 1.1386136e+05],
       [2.0140000e+03, 2.0000000e+00, 2.5300000e+02, ..., 4.3639000e+02,
        3.1374900e+03, 8.7947500e+03]])

In [25]:
test = SelectKBest(score_func=chi2, k=10)

In [26]:
fit = test.fit(X, Y)

In [27]:
np.set_printoptions(precision=3)
print(fit.scores_)

[1.803e-01 2.440e+05 1.526e+07 1.985e+05 1.129e+09 1.044e+09 6.312e+08
 1.922e+09 2.672e+08 6.241e+07 7.041e+07 2.704e+08 2.060e+09]


In [28]:
features = fit.transform(X)

In [29]:
print(features[0:6,:])

[[3.110e+02 1.145e+05 0.000e+00 1.500e+03 1.160e+05 2.103e+04 1.307e+04
  9.369e+03 4.346e+04 1.594e+05]
 [7.900e+02 8.408e+04 0.000e+00 0.000e+00 8.408e+04 1.659e+04 1.246e+04
  6.932e+03 3.598e+04 1.201e+05]
 [5.350e+02 9.980e+03 0.000e+00 7.984e+02 1.078e+04 0.000e+00 2.255e+03
  8.351e+02 3.090e+03 1.387e+04]
 [2.500e+02 2.873e+03 0.000e+00 0.000e+00 2.873e+03 0.000e+00 6.226e+02
  2.225e+02 8.451e+02 3.718e+03]
 [7.900e+02 6.702e+03 0.000e+00 1.767e+02 6.879e+03 0.000e+00 2.712e+03
  5.384e+02 3.250e+03 1.013e+04]
 [2.100e+01 4.532e+04 0.000e+00 0.000e+00 4.532e+04 9.386e+03 1.178e+04
  3.486e+03 2.465e+04 6.997e+04]]


In [30]:
for i in fit.scores_:
    print(i)
    j = np.float64(i).astype(str)
    print(i,"---",j)

0.18028126202013464
0.18028126202013464 --- 0.18028126202013464
243987.53135271353
243987.53135271353 --- 243987.53135271353
15264164.782287844
15264164.782287844 --- 15264164.782287844
198519.52899488626
198519.52899488626 --- 198519.52899488626
1128500200.5776718
1128500200.5776718 --- 1128500200.5776718
1044301147.398399
1044301147.398399 --- 1044301147.398399
631240203.8441801
631240203.8441801 --- 631240203.8441801
1922159670.5243876
1922159670.5243876 --- 1922159670.5243876
267241490.49094096
267241490.49094096 --- 267241490.49094096
62409801.475027405
62409801.475027405 --- 62409801.475027405
70413193.95257759
70413193.95257759 --- 70413193.95257759
270442832.25754124
270442832.25754124 --- 270442832.25754124
2060089250.4379735
2060089250.4379735 --- 2060089250.4379735
